80 rinkinių filtrai
atviriduomenys/katalogas pull request #113
Opened 2022-07-27 07:08 UTC by adp-atea

2022-07-29 09:11 UTC, sirex requested changes
.

2022-07-29 09:11 UTC, sirex commented on locale/lt/LC_MESSAGES/django.po
>  #: vitrina/orgs/apps.py:8
Why this file is here? As I understand, this was generated by https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#localization-how-to-create-language-files?

I suggest, to remove this file for now and to translations separately?

2022-07-29 09:11 UTC, sirex commented on pyproject.toml
> +mysqlclient = "^2.1.1"
I seen this before, but we don't need `mysqlclient`. Please remove.

2022-07-29 09:11 UTC, sirex commented on vitrina/datasets/templates/vitrina/datasets/filters.html
> +        <a href="?status=HAS_DATA" class="category-panel-block" title="Atverti duomenys">
It should be possible to filter by multiple filters, now each filter overrides previous filters. Also, currently active filter is not shown.

I would move all filtering logic out of templates to Python, and in templates, just render prepared data, with all the urls, active filters, etc.

2022-07-29 09:11 UTC, sirex commented on vitrina/datasets/templates/vitrina/datasets/filters.html
> +                           placeholder="{% translate "Data iki" %}">
These days, most browsers have a built-in date picker, do I'm not sure if we need a custom JavaScript implementation for that?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#browser_compatibility

2022-07-29 09:11 UTC, sirex commented on vitrina/datasets/views.py
> +            datasets = datasets.filter(**filter_dict)
It should be possible to add multiple filters.

2022-07-29 11:49 UTC, sirex commented
I found, that this pull request, is based on top of https://github.com/atviriduomenys/katalogas/pull/115, please, separate changes correctly, do not create pull requests multiple times, for same changes.

This pull request should only include filter related changes, search related changes should not be here.

2022-08-22 13:51 UTC, sirex requested changes

2022-08-22 13:51 UTC, sirex commented on tests/test_dataset_filters.py
> +    dataset_structure.save()
```suggestion
    dataset_structure = DatasetStructureFactory(dataset=dataset_has_data)
```

2022-08-22 13:51 UTC, sirex commented on tests/test_dataset_filters.py
> +    assert resp.status == '200 OK'
No need to test status, it is checked by `app.get`.

2022-08-22 13:51 UTC, sirex commented on vitrina/datasets/views.py
> +}
See https://github.com/atviriduomenys/katalogas/pull/112#discussion_r951349613

In other words, this should be defined in `models.py` as model status choices using Django provided functionality.

2022-08-22 13:51 UTC, sirex commented on tests/test_dataset_filters.py
> +    assert resp.context['selected_status'] == HAS_STRUCTURE
Move separate test cases into separate test case functions. And there is no need to run tests on every possible value of an attribute.

2022-08-22 13:51 UTC, sirex commented on tests/test_dataset_filters.py
> +    dataset_with_organization2.save()
```suggestion
    dataset_with_organization1 = DatasetFactory(organization=organization)
    dataset_with_organization2 = DatasetFactory(organization=organization)
```

2022-08-22 13:51 UTC, sirex commented on tests/test_dataset_filters.py
> +    assert len(resp.context['object_list']) == 2
It is much better to test content instead of amount. There can be duplicates in results also order is important in most cases.

2022-08-22 13:51 UTC, sirex commented on vitrina/classifiers/models.py
> +        return parents
Use [django-treebeard's get_ancestors()](https://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.get_ancestors) instead.

2022-08-22 13:51 UTC, sirex commented on vitrina/classifiers/models.py
> +        return all_children
Use [django-treebeard's get_children()](https://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.get_children) instead.

2022-08-22 13:51 UTC, sirex commented on vitrina/classifiers/models.py
> +        return parents
```suggestion
        yield from self.get_parents()
        yield from self.get_children()
```

2022-08-22 13:51 UTC, sirex commented on vitrina/datasets/templates/vitrina/datasets/list.html
> +    <script src="{% static 'js/datepicker.lt-LT.js' %}"></script>
As I understand datepicker is no longer needed?

2022-08-22 13:51 UTC, sirex commented on vitrina/datasets/views.py
> +        return queryset
Move this to a model manager or `services.py`.

2022-08-22 13:51 UTC, sirex commented on vitrina/datasets/views.py
> +        return related_categories
Move to `services.py`.

2022-08-24 14:09 UTC, sirex requested changes

2022-08-24 14:09 UTC, sirex commented on tests/datasets/test_views.py
> +                                                                organization.pk, category.pk, frequency.pk))
```suggestion
    resp = app.get(reverse("dataset-search-results"), {
        'status': Dataset.HAS_DATA,
        'organization': organization.pk,
        'category': category.pk,
        'tags': 'tag1',
        'tags': 'tag2',
        'frequency': frequency.pk,
        'date_from': '2022-01-01',
        'date_to': '2022-02-10',
    })
```

> Beautiful is better than ugly.
> Readability counts.
> -- https://peps.python.org/pep-0020/

2022-08-24 14:09 UTC, sirex commented on tests/datasets/test_views.py
> +                                              organization=organization, category=category, frequency=frequency)
```suggestion
    dataset_with_all_filters = DatasetFactory(
        status=Dataset.HAS_DATA,
        tags="tag1, tag2, tag3",
        published=datetime(2022, 2, 9),
        organization=organization,
        category=category,
        frequency=frequency,
    )
```

> Beautiful is better than ugly.
> Readability counts.
> -- https://peps.python.org/pep-0020/

2022-08-24 14:09 UTC, sirex commented on vitrina/datasets/views.py
> +class DatasetSearchResultsView(ListView):
Please move this into `DatasetListView`, we don't need separate view for search results, we only have on `DatasetListView` which always shows a list of datasets, optionally filtered.

2022-08-24 14:09 UTC, sirex commented on vitrina/datasets/views.py
> +            datasets = datasets.filter(Q(published__gt=date_from) & Q(published__lt=date_to))
```suggestion
        if date_from and date_to:
            datasets = datasets.filter(published__range=(date_from, date_to))
```

https://docs.djangoproject.com/en/3.2/ref/models/querysets/#range

Filtering by dates should be inclusive.

2022-08-24 14:09 UTC, sirex commented on vitrina/datasets/views.py
> +            datasets = datasets.filter(published__gt=date_from)
```suggestion
            datasets = datasets.filter(published__gte=date_from)
```

2022-08-24 14:09 UTC, sirex commented on vitrina/datasets/views.py
> +            datasets = datasets.filter(published__lt=date_to)
```suggestion
            datasets = datasets.filter(published__lte=date_to)
```

2022-08-24 14:09 UTC, sirex commented on vitrina/datasets/views.py
> +        filter_dict = self.request.GET.dict()
Since this is going directly into query it will for sure generate a lot of 500 errors, when some bot passes some GET params. Let's be explicit and only include GET params, that we know are model parameters.

2022-08-24 14:09 UTC, sirex commented on vitrina/datasets/views.py
> +        categories = self.request.GET.getlist('category')
Could you move all filter parameters into a form? We should always validate user input, otherwise we will definitely run into problems.

2022-08-24 14:09 UTC, sirex commented on vitrina/datasets/views.py
> +        return selected_value
Let's keep View classes clean and do not add any helper methods. All view helper functions should go to `helpers.py`.

https://en.wikipedia.org/wiki/Separation_of_concerns
https://en.wikipedia.org/wiki/Single-responsibility_principle

2022-08-24 14:09 UTC, sirex commented on vitrina/datasets/views.py
> +                'query': "?%s%sstatus=%s" % (query, "&" if query else "", key),
It looks, that new filters are always appended on top of existing ones. I think, better way to handle this, is to have `query` as a dict and update it, replacing or appending previously set values. Then you can simply [urlencode](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode) dict Also, please move this url building functionality into a separate function in `helpers.py` and add tests for it. The end result could look like this:

```suggestion
                'query': get_filter_url(query, 'status', key, append=False),
```

2022-08-29 10:17 UTC, sirex requested changes

2022-08-29 10:17 UTC, sirex commented on vitrina/datasets/views.py
> +        filter_form.is_valid()
If form is not valid, an error page should be shown, instead of continuing even with invalid user input.

2022-08-29 10:17 UTC, sirex commented on vitrina/helpers.py
> +def get_filter_url(request, key, value, append=False):
```suggestion
def get_filter_url(request: Request, key: str, value: Any, append: bool = False) -> str:
```

2022-08-29 10:17 UTC, sirex commented on vitrina/helpers.py
> +def get_selected_value(request, title, multiple=False, is_int=True):
```suggestion
def get_selected_value(request: Request, title: str, multiple: bool = False, is_int: bool = True) -> Optional[List[Any]]:
```

2022-08-30 16:16 UTC, sirex requested changes
I still see translations files. What I meant in previous comment, that translation files should net be in this pull request, now they are deleted from `devel`.

https://git-scm.com/docs/git-restore

Same thing applies to static files, static files should not by added to version control, they should be managed by an asset manager.

https://webpack.js.org/guides/getting-started/

2022-09-01 05:27 UTC, adp-atea commented
As I understand the last change will be done with another task, so putting to review.

2022-09-09 14:18 UTC, sirex requested changes

2022-09-09 14:18 UTC, sirex commented on vitrina/datasets/views.py
> +            return HttpResponseServerError()
Please, respect the interface, `get_queryset` must return `QuerySet`, not `HttpResponse`. In order to handle this correctly, you need to move form validation into `get` method where, you can return `HttpResponse`. When you follow the interface, you don't have to resort to hacks like `hasattr(self.object_list, 'status_code')`.

Also, we need to return a [HttpResponseBadRequest](https://docs.djangoproject.com/en/3.2/ref/request-response/#django.http.HttpResponseBadRequest), not a server error.

See also:

- https://github.com/django/django/blob/stable/3.2.x/django/views/generic/list.py#L141-L158
- https://docs.djangoproject.com/en/3.2/ref/class-based-views/generic-display/#listview
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses

2022-09-13 08:07 UTC, sirex approved these changes

2022-09-13 10:44 UTC, merged