88 organizacijos peržiūra
atviriduomenys/katalogas pull request #129
Opened 2022-08-12 11:49 UTC by adp-atea

2022-08-24 13:06 UTC, sirex requested changes
As I understand this also implements:

- #89
- #131

I associated this pull request with these issues.

2022-08-24 13:06 UTC, sirex commented on tests/test_organization_detail.py
> +    assert True is resp.context['datasets_active']
Move this file to `tests/orgs/test_views.py`.

2022-08-24 13:06 UTC, sirex commented on vitrina/orgs/urls.py
> +    path('orgs/<kind>/<slug:slug>/', OrganizationDetailView.as_view(), name='organization-detail'),
```suggestion
    path('orgs/<str:kind>/<slug:slug>/', OrganizationDetailView.as_view(), name='organization-detail'),
```

2022-08-24 13:06 UTC, sirex commented on vitrina/orgs/templates/vitrina/orgs/tabs.html
> +        {% if members %}
Narių sąrašą turi rodyti visais atvejais, net jei ir nėra narių. Nes narių sąraše bus naujo nario pridėjimo forma.

2022-08-24 13:06 UTC, sirex commented on vitrina/orgs/templates/vitrina/orgs/tabs.html
> +        {% if datasets %}
Visada turi rodyti rinkinių sąrašą, net jei ir nėra rinkinių, nes tame puslapyje bus organizacijos rinkinių administravimas.

2022-08-24 13:06 UTC, sirex commented on vitrina/orgs/views.py
> +            'datasets': organization.dataset_set.all(),
In organization details page members and datasets should not be pulled from database. I mean, organization members and datasets tabs should always be visible, even if organization does not have any members and/or datasets.

2022-08-24 13:06 UTC, sirex commented on vitrina/orgs/views.py
> +            'datasets_active': False
```suggestion
            'url_name': request.resolver_match.url_name,
```

Then in templates, you can simply check `if url_name == 'organization-detail'`. This way you will have less tings to care about. Also, `request` is already available in template, so probably there is no need to set this context variable at all.

2022-08-24 13:06 UTC, sirex commented on vitrina/orgs/templates/vitrina/orgs/tabs.html
> +        <li class="{%if detail_active %} is-active {% endif %}">
```suggestion
        <li class="{%if request.resolver_match.url_name == 'organization-detail' %} is-active {% endif %}">
```

2022-08-24 13:06 UTC, sirex commented on vitrina/orgs/models.py
> +class Organization(AL_Node):
Is there a reason for AL tree? Documentation says:

> The adjacency list model has the advantage of fast writes at the cost of slow reads. If you read more than you write, use [MP_Node](https://django-treebeard.readthedocs.io/en/latest/mp_tree.html#treebeard.mp_tree.MP_Node) instead.
> -- https://django-treebeard.readthedocs.io/en/latest/al_tree.html

Reads will be more common than writes, so I would agree with the documentation, to better use `MP_Node`?

2022-08-24 13:06 UTC, sirex commented on vitrina/orgs/models.py
> +        pass
These methods will not be needed with `MP_Node`.

2022-08-24 13:06 UTC, sirex commented on tests/test_organization_detail.py
> +    assert resp.context['members'][0].pk == representative.pk
```suggestion
    assert list(resp.context['members']) == [representative]
```

2022-08-24 13:06 UTC, sirex commented on tests/test_organization_detail.py
> +    assert resp.context['datasets'][0].pk == dataset.pk
```suggestion
    assert list(resp.context['datasets']) == [dataset]
```

2022-08-24 13:06 UTC, sirex commented on vitrina/orgs/migrations/0004_alter_organization_options.py
> +    ]
It looks like an error? Previous migration sets `managed` to `Ture`, and this one sets it back to `False`?

2022-08-24 13:06 UTC, sirex commented on vitrina/orgs/models.py
>          managed = False
Since schema of this model has changed, this line must be removed. We only keep `managed = False` for those models, that don't have any changes in schema.

2022-08-24 13:06 UTC, sirex commented on vitrina/orgs/templates/vitrina/orgs/datasets.html
> +                <td>{{ forloop.counter }}.</td>
I think, we don't need this.

2022-08-24 13:06 UTC, sirex commented on vitrina/orgs/templates/vitrina/orgs/parent_list.html
> +    {% include "vitrina/orgs/parent_list.html" with parent=parent.parent %}
Is this a recursive template? Doesn't look like a good idea, lets keep data access to models and treebeard, they are far more efficient at this. You can get list of all ancestors with [get_ancestors()](https://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.get_ancestors).

2022-08-24 13:06 UTC, sirex commented on vitrina/orgs/templates/vitrina/orgs/members.html
> +                <td>{{ forloop.counter }}.</td>
I don't see a point in showing member position number in this list. So I suggest removing it?

2022-08-24 13:06 UTC, sirex commented on vitrina/orgs/templates/vitrina/orgs/list.html
> +                                <strong><a href="/orgs/{{ i.kind }}/{{ i.slug }}" class="dataset-list-title">{{ i.title }}</a></strong>
```suggestion
                                <strong><a href="{{ i.get_absolute_url }}" class="dataset-list-title">{{ i.title }}</a></strong>
```

Do not hardcode urls, instead reverse url by url name.

https://docs.djangoproject.com/en/3.2/topics/http/urls/#reverse-resolution-of-urls

2022-08-24 13:06 UTC, sirex commented on vitrina/orgs/templates/vitrina/orgs/datasets.html
> +                <td><a href="{% url 'dataset-detail' d.slug %}">{{ d.title }}</a></td>
```suggestion
                <td><a href="{{ d.get_absolute_url }}">{{ d.title }}</a></td>
```

https://docs.djangoproject.com/en/3.2/ref/models/instances/#django.db.models.Model.get_absolute_url

2022-08-24 13:06 UTC, sirex commented on vitrina/orgs/templates/vitrina/orgs/datasets.html
> +                <td>{{ d.description }}</td>
```suggestion
                <td>{{ d.description|truncatewords:12 }}</td>
```

2022-08-24 13:06 UTC, sirex commented on vitrina/orgs/templates/vitrina/orgs/detail.html
> +	                {% if organization.kind == 'gov' and organization.parent %}
```suggestion
	                {% if organization.parent %}
```

2022-08-24 13:06 UTC, sirex commented on vitrina/settings.py
> +            'MIGRATE': False
Maybe it is better to control this from test runner?

https://pytest-django.readthedocs.io/en/latest/database.html#no-migrations-disable-django-migrations

2022-08-25 10:07 UTC, adp-atea commented on vitrina/orgs/models.py
> +class Organization(AL_Node):
Tried using MP_Node, the problem with this class is that we're using it on existing model with existing data. It requires to populate path field for existing organizations, however path field is unique and can't be populated just by giving some default value. I can try writing a method in migration, which would assign values to path. But is using MP_Node really better solution then?

2022-08-25 12:29 UTC, sirex commented on vitrina/orgs/models.py
> +class Organization(AL_Node):
Previously organizations table was flat, so it is easy to populate default values. Here is an example migration:

https://gist.github.com/archatas/10808f9acf61afa0401bb05c9464d32a

For `path`, you need to set `"0000"` as default value.

2022-08-25 12:30 UTC, sirex commented on vitrina/orgs/models.py
> +class Organization(AL_Node):
`MP_Node` is best for reads, and organizations will be created basically once, so we want to optimize for reads.

2022-08-29 09:00 UTC, sirex requested changes

2022-08-29 09:00 UTC, sirex commented on vitrina/orgs/views.py
> +        organization = context_data.get('organization')
```suggestion
        organization: Organization = self.object
```

2022-08-29 09:00 UTC, sirex commented on vitrina/orgs/views.py
> +        organization = context_data.get('organization')
```suggestion
        organization: Organization = self.object
```

2022-08-29 09:00 UTC, sirex commented on vitrina/orgs/views.py
> +        organization = context_data.get('organization')
```suggestion
        organization: Organization = self.object
```

2022-08-29 09:00 UTC, sirex commented on vitrina/orgs/views.py
> +class OrganizationDatasetsView(OrganizationDetailView):
I think there should be no such thing as `OrganizationDatasetsView`, instead this functionality should be built on top of `DatasetListView`, with organization filter.

Browsing and managing dataset list will be one of the key functions, so I think we don't want to duplicate effort and replicate same functionality in multiple places. That is why, I think, that organization datasets should simply bet normal dataset list, just shown in organization context, which is determined by url name.

2022-08-29 09:00 UTC, sirex commented on vitrina/orgs/templates/vitrina/orgs/datasets.html
> +{% endblock %}
Reuse `vitrina/datasets/templates/vitrina/datasets/list.html`, we will need all the functionality available there, like filters, search and etc. So we don't need separate dataset list for organization.

The only thing we need, is to show dataset list in organization context, showing organization tabs.

2022-08-30 15:50 UTC, sirex requested changes

2022-08-30 15:50 UTC, sirex commented on vitrina/datasets/views.py
> +            datasets = Dataset.public.filter(organization=organization)
Let's be consistent and check if this is organization datasets list by checking `request.resolver_match.url_name`, same way as it is done in templates. And if request URL is organization datasets, then we should throw 404 if organization not found.

2022-08-30 15:50 UTC, sirex commented on vitrina/templates/component/hero.html
>                                  <a href="/organizations" class="stats">
Do not hardcode urls.

2022-08-30 15:50 UTC, sirex commented on vitrina/templates/component/hero.html
>                                  <a href="/datasets" class="stats">
Do not hardcode urls.

2022-08-30 15:50 UTC, sirex commented on vitrina/templates/component/hero.html
>                                  <a href="/projects" class="stats">
Do not hardcode urls.

2022-09-07 09:07 UTC, sirex requested changes

2022-09-07 09:07 UTC, sirex commented on vitrina/datasets/views.py
> +            datasets = Dataset.public.filter(organization=organization)
This way you will loose ordering set previously, maybe

```suggestion
            datasets = datasets.filter(organization=organization)
```

?

2022-09-09 09:31 UTC, sirex approved these changes

2022-09-09 09:38 UTC, merged