96 struktūros peržiūra
atviriduomenys/katalogas pull request #141
Opened 2022-09-06 07:53 UTC by adp-atea

2022-09-09 15:25 UTC, sirex requested changes

2022-09-09 15:25 UTC, sirex commented on tests/datasets/test_views.py
> +    }), expect_errors=True)
```suggestion
    resp = app.get(dataset_structure_data["dataset1"].get_absolute_url(), expect_errors=True)
```

Same thing below.

2022-09-13 10:37 UTC, adp-atea commented
This was in done, but it's not approved, so I can't merge it.

2022-09-13 11:39 UTC, sirex requested changes

2022-09-13 11:39 UTC, sirex commented on tests/datasets/test_views.py
> +    assert resp.context['structure_data'] == []
Could you also add a test for download option?

2022-09-13 14:13 UTC, sirex approved these changes

2022-09-14 05:17 UTC, merged