117 turinio vertinimas spaudžiant „Patinka“
atviriduomenys/katalogas pull request #162
Opened 2022-09-21 10:21 UTC by adp-atea

2022-09-27 07:05 UTC, sirex requested changes
Neveikia migracijos.

```
$ poetry run python manage.py migrate
  Applying vitrina_likes.0002_auto_20220921_0933...
Traceback (most recent call last):
[...]
  File "vitrina/likes/migrations/0002_auto_20220921_0933.py", line 13, in migrate_likes
    content_type = ContentType.objects.get(app_label='vitrina_requests', model='request')
  File "django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(__fake__.ContentType.DoesNotExist: ContentType matching query does not exist.
```

2022-09-28 13:34 UTC, sirex requested changes
Migrations are still failing:

```
$ poetry run python manage.py migrate
  Applying vitrina_datasets.0001_initial...
Traceback (most recent call last):
  File "django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.DuplicateTable: relation "dataset" already exists
```

I thing, something has slipped into `devel`, now most pull requests fail with the same error.

2022-09-28 16:10 UTC, adp-atea commented
Migration error was fixed with #119 task. I rebased this on top of devel after merging #119 into it. It should work now.

2022-09-28 20:19 UTC, sirex approved these changes

2022-09-29 05:53 UTC, merged