119 turinio prenumerata
atviriduomenys/katalogas pull request #164
Opened 2022-09-22 07:15 UTC by adp-atea

2022-09-27 07:16 UTC, sirex requested changes
Migrations does not work.

```
$ poetry run python manage.py migrate
  Applying vitrina_messages.0002_subscription...
Traceback (most recent call last):
[...]
  File "vitrina/messages/migrations/0002_subscription.py", line 14, in migrate_subscriptions
    content_type = ContentType.objects.get(app_label='vitrina_datasets', model='dataset')
  File "django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
__fake__.ContentType.DoesNotExist: ContentType matching query does not exist.
```

2022-09-27 10:26 UTC, adp-atea commented
I fixed dataset initial migration and went through the whole process of creating docker image, migrating MySQL database to PostgeSQL, creating some test data for migration that gives errors and then running the migrate command. Everything went smoothly. Is it possible that in this case you didn't run contenttypes migrations or the database got corrupted somehow?

2022-09-27 14:10 UTC, sirex requested changes
> I fixed dataset initial migration and went through the whole process of creating docker image, migrating MySQL database to PostgeSQL, creating some test data for migration that gives errors and then running the migrate command. Everything went smoothly. Is it possible that in this case you didn't run contenttypes migrations or the database got corrupted somehow?

Fixed this in https://github.com/atviriduomenys/katalogas/pull/164/commits/2f7dc5c346dc85eaec3cbafd073aeaaae586edd7, the issue was, that you tried to access `ContentType` directly, but `get_for_model()` manager method should be used, because `ContentType` uses database as a cache and records might or might not be cached, especially during migrations.

2022-09-27 14:10 UTC, sirex commented on vitrina/messages/models.py
> +    content_object = GenericForeignKey('content_type', 'object_id')
`user`, `content_type` and `object_id` should be [unique_together](https://docs.djangoproject.com/en/3.2/ref/models/options/#unique-together), to prevent duplicate subscriptions.

2022-09-28 11:39 UTC, sirex approved these changes

2022-09-28 13:54 UTC, merged