Remade dataset tagging with django-tagulous
atviriduomenys/katalogas pull request #165
Opened 2022-09-23 09:06 UTC by adp-atea

2022-09-26 08:30 UTC, sirex requested changes
When running `poetry run python manage.py migrate` I get following error:

```python
  Applying vitrina_orgs.0005_representative_organization...
Traceback (most recent call last):
  File "django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DuplicateColumn: column "organization_id" of relation "representative" already exists
```

2022-09-27 06:42 UTC, sirex requested changes
Migrations do not work:

```
$ poetry run python manage.py migrate
  Applying vitrina_datasets.0004_auto_20220923_1151...
Traceback (most recent call last):
  File "/home/sirex/.cache/pypoetry/virtualenvs/vitrina-dJ5t4DVf-py3.10/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DuplicateColumn: column "dataset_id" of relation "dataset_structure" already exists
```

2022-10-07 12:32 UTC, sirex requested changes
Migrations do not work:

```python
  Applying vitrina_datasets.0004_auto_20220923_1151...
Traceback (most recent call last):
  File "django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DuplicateColumn: column "dataset_id" of relation "dataset_structure" already exists
```

2022-10-12 09:42 UTC, sirex requested changes

2022-10-12 09:42 UTC, sirex commented on pyproject.toml
> +elasticsearch = "7.8.1"
Why is this needed?

2022-10-12 09:42 UTC, sirex commented on tests/datasets/test_views.py
> +    assert len(resp.context['tags']) == 0
Previous check was much better, because many things can return `len() == 0`, for example empty string, So checking for `== []` also gives as type checking, which is important.

2022-10-12 09:42 UTC, sirex commented on vitrina/datasets/models.py
> +        return names
```suggestion
        return list(self.tags.all())
```

2022-10-12 09:42 UTC, sirex commented on vitrina/datasets/models.py
> +    tags = tagulous.models.TagField(blank=True)
```suggestion
    tags = tagulous.models.TagField(
        blank=True,
        force_lowercase=True,
        space_delimiter=False,
        autocomplete_limit=20,
        verbose_name=_("Žymės"),
        help_text=_("Pateikite kableliu atskirtą sąrašą žymių."),
    )
```

- [force_lowercase](https://radiac.net/projects/django-tagulous/documentation/tag_options/#option_force_lowercase)
- [space_delimiter](https://radiac.net/projects/django-tagulous/documentation/tag_options/#option_space_delimiter)
- [autocomplete_limit](https://radiac.net/projects/django-tagulous/documentation/tag_options/#option_autocomplete_limit)

Also, autocomplete should show first 20 tags, sorted by most frequently used tags on top. Not sure if this only possible with creating a custom [autocomplete_view](https://radiac.net/projects/django-tagulous/documentation/tag_options/#option_autocomplete_settings), or there is an easier way.

Also

![image](https://user-images.githubusercontent.com/297583/195296819-5ebdcf24-c4b6-4959-b240-17ac06fb8c98.png)

maybe there is a way to fix how fields is displayed?

Maybe check [autocomplete_settings](https://radiac.net/projects/django-tagulous/documentation/tag_options/#option_autocomplete_settings)?

2022-10-12 09:42 UTC, sirex commented on vitrina/datasets/migrations/0006_remake_tags.py
> +            dataset.tags.add(tag.strip())
Add more cleaning to the tags:

- do not add empty tags
- convert all tags to lowercase
- strip('"')
- strip('.')

2022-10-12 09:42 UTC, sirex commented on vitrina/datasets/search_indexes.py
> +    tags = MultiValueField(model_attr='get_tag_list', faceted=True, null=True)
```suggestion
    tags = MultiValueField(model_attr='get_tag_list', faceted=True)
```

2022-10-12 11:25 UTC, adp-atea commented on pyproject.toml
> +elasticsearch = "7.8.1"
To specify elasticsearch version, so that poetry update would not update it. The version must be 7.8.1 or it does not work.

2022-10-13 06:46 UTC, sirex commented on vitrina/datasets/models.py
> +    tags = tagulous.models.TagField(blank=True)
Stiliaus sutvarkymas iškeltas į https://github.com/atviriduomenys/katalogas/issues/199

2022-10-17 14:35 UTC, sirex approved these changes

2022-10-18 05:47 UTC, merged