176 nuasmenintas dumpas
atviriduomenys/katalogas pull request #178
Opened 2022-09-29 10:55 UTC by adp-atea

2022-09-30 18:43 UTC, sirex requested changes
I added some changes, but the issue is, that anonymization must be done on initial data, before Django migrations are applied, because we want to know if migrations will work.

I suggest moving this out of Django management command into `scripts/anonymize.py` and do the anonymization using [dataset](https://dataset.readthedocs.io/).

The process should look like this:

1. Move data from MySQL to PostgreSQL using pgloader.
2. Run `poetry run python scripts/anonymize.py` on the PostgreSQL database.
3. Run `poetry run manage.py migrate`.

This way we will have more reliable data for migrations.

2022-10-03 10:33 UTC, adp-atea commented
Note that because we're anonymizing data before migrations,  we should change user password length to be longer in MySQL dump file by hand, otherwise anonymize script will not be able to save changed passwords.

2022-10-04 13:36 UTC, sirex requested changes

2022-10-04 13:36 UTC, sirex commented on scripts/anonymize.py
> +                'password': make_password("secret")
We should use exactly the same hashing algorithm as it was used before the migration. We want to be as close as possible to the original production environment.

2022-10-04 13:36 UTC, sirex commented on resources/adp-dev.sql
> +  `password` char(255) COLLATE utf8mb4_lithuanian_ci DEFAULT NULL,
We should stick to the original password hashing algorithm and should not change the schema.

2022-10-05 11:33 UTC, sirex requested changes
I see that depending on factories is not a good idea, because `Representative` and its factory will change significantly, so we can't relay on factories.

Could you remove dependency from factories and generate names, emails, etc. using [Faker](https://faker.readthedocs.io/en/master/providers/faker.providers.person.html) directly?

2022-10-05 19:06 UTC, sirex approved these changes

2022-10-06 05:47 UTC, merged