135 webpack
atviriduomenys/katalogas pull request #187
Opened 2022-10-06 11:04 UTC by adp-atea

2022-10-10 09:51 UTC, sirex requested changes

2022-10-10 09:51 UTC, sirex commented on Makefile
> +	npm run build
This Makefile is useless, so I thing it is better to just update README and remove Makefile. Maybe some time later, someone will create a proper Makefile.

2022-10-10 09:51 UTC, sirex commented on vitrina/templates/base.html
> +    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
Shouldn't this come from webpack?

2022-10-10 09:51 UTC, sirex commented on webpack/package.json
> +  "name": "webpack",
```suggestion
  "name": "vitrina",
```

2022-10-10 09:51 UTC, sirex commented on webpack/package.json
> +    "jquery": "^3.6.1"
Why bulma is in `devDepencencies` and `jquery` is not?

2022-10-10 09:51 UTC, sirex commented on webpack/src/css/custom/adp.css
> +  background: url("../../../vitrina/static/img/header-bg.png");
Use [resolve.alias](https://webpack.js.org/configuration/resolve/#resolvealias) in webpack.config.js. And to the same in other places.

2022-10-10 09:51 UTC, sirex commented on vitrina/static/robots.txt
> -Disallow: /admin
Why this file was deleted? It is needed to prevent search bots from indexing admin.

2022-10-10 09:51 UTC, sirex commented on webpack/webpack.config.js
> +      filename: 'css/adp-final.css'
Can we name it `css/bundle.css`? To match `js/bundle.js`?

2022-10-10 09:51 UTC, sirex commented on vitrina/datasets/templates/vitrina/datasets/detail.html
>      <script src="{% static 'hitcount/jquery.postcsrf.js' %}"></script>
This should be included into webpack. In order to do that, first you need to collect static files:

    poetry run python manage.py collectstatic

An then add directory where static files are collected into [resolve.modules](https://webpack.js.org/configuration/resolve/#resolvemodules) and then import this this file as webpack module. And do the same for other places where postcsrf.js is used.

Currently `collectstatic` collects static files into `static/` directory, this should go into `var/static/`. You can change that in settings `STATIC_ROOT`.

2022-10-12 09:10 UTC, adp-atea commented on vitrina/templates/base.html
> +    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
For some reason jquery works only in javascript files, that are bundled with webpack, it doesn't work in templates. I think I have tried everything from https://github.com/webpack/webpack/issues/4258 but still can't find a way for this to work.

2022-10-12 10:05 UTC, sirex approved these changes

2022-10-12 10:14 UTC, merged