198 partner API - API key migration
atviriduomenys/katalogas pull request #209
Opened 2022-11-04 07:39 UTC by adp-atea

2022-11-04 07:47 UTC, adp-atea commented
As the task required, there will be couple pull requests. This is the first pull request with API key migration and option to generate API keys in Representative form.

2022-11-09 13:20 UTC, sirex requested changes
Mostly looks good, just minor comments.

2022-11-09 13:20 UTC, sirex commented on vitrina/api/migrations/0003_apikey_representative.py
> +                rep.save()
Delete all ApiKey's where representative is not set. There will no longer be organization-wide keys.

2022-11-09 13:20 UTC, sirex commented on vitrina/orgs/views.py
> +                api_key=str(uuid.uuid4()),
Previously for secret keys uuid4 was used, but it is not really meant for this, So I suggest to use more secure [secrets.token_urlsafe()](https://docs.python.org/3/library/secrets.html#secrets.token_urlsafe) function.

```suggestion
                api_key=secrets.token_urlsafe(),
```

2022-11-10 15:00 UTC, sirex approved these changes

2022-11-10 15:00 UTC, sirex commented on vitrina/api/migrations/0003_apikey_representative.py
> +            key.delete()
```suggestion
    ApiKey.objects.filter(representative__isnull=True).delete()
```

Electricity is expensive these days, so please, do not burn CPU if this is not needed.

2022-11-11 06:21 UTC, merged