218 vertimas į anglų kalbą
atviriduomenys/katalogas pull request #225
Opened 2022-11-14 10:07 UTC by adp-atea

2022-11-27 11:52 UTC, sirex requested changes

2022-11-27 11:52 UTC, sirex commented on locale/en/LC_MESSAGES/django.po
> +msgid "ambiguous option: %(option)s could match %(matches)s"
We need only messages, from `vitrina` package, not from all other packages.

2022-12-14 10:00 UTC, sirex requested changes
Looks good, but it would be good to fix messages like `dataset.status` by replacing to natural lithuanian language. This will probably require opening page were a message was used in order to understand what message is supposed to be shown.

2022-12-14 10:00 UTC, sirex commented on vitrina/locale/en/LC_MESSAGES/django.po
> +msgid "dataset.status"
Please also fix these messages, by replacing them into a human readable lithuanian text and translating it to english.

2022-12-15 11:25 UTC, adp-atea commented on vitrina/locale/en/LC_MESSAGES/django.po
> +msgid "dataset.status"
Fixed instances like this that I could find, but for example harvested value inside coretable.html needs to have some functionality tied to it, for now added it as an empty string and wrote a TODO for it.

2023-01-02 10:20 UTC, sirex approved these changes

2023-01-02 12:19 UTC, merged