198 partner API - Datasets, Distributions, Structures
atviriduomenys/katalogas pull request #229
Opened 2022-11-22 12:25 UTC by adp-atea

2022-11-22 13:22 UTC, adp-atea commented
This should be checked after #216 is merged to devel and then this is rebased on devel, because this code depends on #216 code.

2022-12-01 12:35 UTC, sirex requested changes

2022-12-01 12:35 UTC, sirex commented on vitrina/api/views.py
> +        return super().list(request, *args, **kwargs)
This should list datasets of representative organization, but as I understand, currently it shows all datasets? All APIs show operate only on a single organization scope.

Also, API should return all datasets, both published and not yet published.

I will not comment in other places, but all APIs should be restricted to a single organization, that representative is assigned to. That applies to all actions, reading, created, changing, etc.

2022-12-01 12:35 UTC, sirex commented on tests/api/test_views.py
> +    dataset = DatasetFactory()
Add more datasets with different orgs, this api endpoint should only return datasets of representative org and should also return non-public datasets.

2022-12-05 18:05 UTC, sirex requested changes

2022-12-05 18:05 UTC, sirex commented on vitrina/api/views.py
> +            return Dataset.objects.filter(organization=organization)
```suggestion
            return Dataset.objects.filter(organization=organization, deleted__isnull=True)
```

We need to exclude deleted datasets.

2022-12-05 18:05 UTC, sirex commented on vitrina/api/permissions.py
> +        if get_api_key_organization(request):
We will need organization in almost all view, so I think, it is better to set organization on view instance?

2022-12-05 18:05 UTC, sirex commented on vitrina/api/views.py
> +        organization = get_api_key_organization(self.request)
I think, organization should be set on view instance from `APIKeyPermission` in order to avoid parsing headers and querying database multiple times.

2022-12-05 18:05 UTC, sirex commented on vitrina/api/urls.py
> +    path('partner/api/1/datasets/', DatasetViewSet.as_view({
```suggestion
    path('partner/api/1/datasets', DatasetViewSet.as_view({
```

Original API did not have trailing slashes, so we should be fully backwards compatible. Same thing applies to other routes.

2022-12-05 18:05 UTC, sirex commented on vitrina/api/serializers.py
> +        instance.organization = get_api_key_organization(request)
Get organization from `self.context['view'].organization`, which should be added by permission handling or during request handling phase, do not parse headers multiple times, especially in response handling phase.

2022-12-05 18:05 UTC, sirex commented on vitrina/api/serializers.py
> +        set_comment(Dataset.EDITED)
It would be nice to set user too, we know the user from ApiKey (representative.user). Same thing applies to other places.

2022-12-05 18:05 UTC, sirex commented on vitrina/api/serializers.py
> +    size = serializers.IntegerField(required=False, label="", source="file_size")
Maybe we should get file size from `size` source, not from a physical file? Now I'm getting `ValueError: The 'file' attribute has no file associated with it.` errors. So either this, or first fix the https://github.com/atviriduomenys/katalogas/issues/235.

2022-12-07 10:18 UTC, adp-atea commented on vitrina/api/serializers.py
> +    size = serializers.IntegerField(required=False, label="", source="file_size")
For now changed to size attribute, later will fix it with #235 task.

2022-12-07 17:11 UTC, sirex approved these changes

2022-12-08 06:09 UTC, merged