84 allauth backendas viisp
atviriduomenys/katalogas pull request #230
Opened 2022-11-22 13:21 UTC by adp-atea

2023-06-08 12:26 UTC, sirex requested changes

2023-06-08 12:26 UTC, sirex commented on .env
> +VIISP_AUTH_PRIVATE_KEY=LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQ2JuUWpnQm5BRWJFcUcKdGdOTHFyQ2dZS3ZMV2Y2UmtJdml0SWptS1NycXl1M3hyUUNhRG9r
Move this to Django admin.

2023-06-08 12:26 UTC, sirex commented on manage.py
Tikriausiai čia to failo nereikia?

2023-06-08 12:26 UTC, sirex commented on vitrina/users/templates/vitrina/users/login.html
> +        </div>
Perkelti žemiau username/password laukų, ir dinamiškai rodyti visus prisijungimo būdus. Panašiai kaip čia:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/09d77039-37e5-4f69-962f-d37f64361123)

2023-06-08 12:26 UTC, sirex commented on vitrina/viisp/xml_utils.py
> +callback_url = 'http://127.0.0.1:8000/accounts/accounts/viisp/complete-login'
Neturėtu būti įhardocintas.

2023-06-08 12:26 UTC, sirex commented on pyproject.toml
> +signxml = "3.0.0"
Reikėtų paaiškinti komentare, kodėl būtent tokia versija.

2023-06-30 04:42 UTC, Faustasm commented on vitrina/users/templates/vitrina/users/login.html
> +        </div>
Sukuriam atskira taską tam.

2023-06-30 07:01 UTC, sirex requested changes

2023-06-30 07:01 UTC, sirex commented on .env
> +VIISP_AUTHORIZE_URL=https://test.epaslaugos.lt/portal/external/services/authentication/v2
Ar abu URL yra reikalingi?

2023-06-30 07:01 UTC, sirex commented on vitrina/orgs/views.py
> +        org_count = len(Organization.objects.all())
Organization.objects.count()

2023-06-30 07:01 UTC, sirex commented on vitrina/orgs/views.py
> +        self.org.depth = 1
https://django-treebeard.readthedocs.io/en/latest/tutorial.html

```python
Organization.add_root(name='Org name')
```

2023-06-30 07:01 UTC, sirex commented on vitrina/orgs/forms.py
> +            ))
Neturėtu būti klaida, jei organizacija egzistuoja, tada tiesiog priskiriam tai organizacijai koordinatorių.  Ateityje organizacijos bus importuojamos ir vos egzistuos.

2023-06-30 07:02 UTC, sirex approved these changes

2023-06-30 12:17 UTC, Faustasm commented on pyproject.toml
> +signxml = "3.0.0"
Fixed with last commit

2023-06-30 12:18 UTC, Faustasm commented on .env
> +VIISP_AUTHORIZE_URL=https://test.epaslaugos.lt/portal/external/services/authentication/v2
Taip. Antras naudojamas generuot redirect į valdžios vartus.

2023-06-30 12:19 UTC, Faustasm commented on vitrina/orgs/forms.py
> +            ))
Fixed

2023-06-30 12:25 UTC, Faustasm commented on vitrina/orgs/views.py
> +        self.org.depth = 1
Pataisyta ir nauja užduotis https://github.com/atviriduomenys/katalogas/issues/369

2023-06-30 12:27 UTC, merged