:sparkles: Filters and search for requests with index
atviriduomenys/katalogas pull request #311
Opened 2023-05-10 05:42 UTC by Faustasm

2023-05-25 12:54 UTC, sirex requested changes

2023-05-25 12:54 UTC, sirex commented on vitrina/requests/templates/vitrina/requests/filters.html
> +        <strong>{% translate "Rinkinio būsena" as datasetStatus %}{{ datasetStatus|upper}}</strong>
![image](https://github.com/atviriduomenys/katalogas/assets/297583/9fe2062c-f254-4de0-bd2a-4f0d99fb45a2)

Reikėtų įtraukti dar vieną punktą „Nepriskirta“, kuris rodytų kiek yra poreikių, nepriskirtų nei vienam rinkiniui.

Taip pat, virš „Rinkinio būsena“ reikėtų dar vieno filtro „Poreikio būsena“, kuri rodytų ne rinkinių, o poreikių būsenas.

2023-05-25 12:54 UTC, sirex commented on vitrina/requests/templates/vitrina/requests/filters.html
> +        <strong>{% translate "Grupė" as catTitle %} {{catTitle|upper}}</strong>
![image](https://github.com/atviriduomenys/katalogas/assets/297583/a4c2fe70-063b-4b02-8fc4-492a8c57d829)

Nerodyti grupių filtro, jei nėra nei vienos grupės.

2023-05-25 12:54 UTC, sirex commented on vitrina/requests/templates/vitrina/requests/filters.html
> +</nav>
Trūksta dar vieno filtro, pagal veiklos sritis:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/205540da-f0da-4a19-93bc-682a92bc8605)

2023-05-25 12:54 UTC, sirex commented on vitrina/requests/templates/vitrina/requests/filters.html
> +        <strong>{% translate "Organizacija" as orgTitle %} {{orgTitle|upper}}</strong>
Kažkas blogai su organizacijų filtru, dabar matau tokius skaičius:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/f24debd6-0659-489e-abde-d21a429f6351)

Nors turėtu būti, kažkas panašaus į tai:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/f2ef3cc1-1336-4af6-8338-743680d4c08a)

Taip pat reikėtų įtraukti vieną filtrą „Nepriskirta“, kuris rodytų, keik yra poreikių, nepriskirtų jokiai organizacijai, o pasirinkus šį filtrą, rodytų poreikius, kurie nepriskirti jokiai organizacijai.

2023-05-25 12:54 UTC, sirex commented on vitrina/requests/templates/vitrina/requests/filters.html
> +        <strong>{% translate "Registravimo data" as regDate %} {{ regDate | upper }}</strong>
Papildomai, datos pasirinkimui nuo/iki reikėtų rodyti tą patį, kas yra aprašyta čia: https://github.com/atviriduomenys/katalogas/issues/314

2023-05-25 13:20 UTC, sirex requested changes

2023-05-25 13:20 UTC, sirex commented on vitrina/requests/templates/vitrina/requests/list.html
>                     class="button is-primary m-t-xs m-b-lg">{% translate "Teikti poreikį" %}</a>
Teikti poreikį migtukas turėtu būti filtrų viršuje.

2023-08-03 04:31 UTC, Faustasm commented on vitrina/requests/templates/vitrina/requests/filters.html
> +        <strong>{% translate "Rinkinio būsena" as datasetStatus %}{{ datasetStatus|upper}}</strong>
Fixed

2023-08-03 04:31 UTC, Faustasm commented on vitrina/requests/templates/vitrina/requests/filters.html
> +        <strong>{% translate "Grupė" as catTitle %} {{catTitle|upper}}</strong>
Fixed

2023-08-03 04:31 UTC, Faustasm commented on vitrina/requests/templates/vitrina/requests/filters.html
> +        <strong>{% translate "Organizacija" as orgTitle %} {{orgTitle|upper}}</strong>
Fixed

2023-08-03 04:31 UTC, Faustasm commented on vitrina/requests/templates/vitrina/requests/filters.html
> +        <strong>{% translate "Registravimo data" as regDate %} {{ regDate | upper }}</strong>
Fixed

2023-08-14 06:08 UTC, sirex commented
Kodėl šitas pull request uždarytas?

2023-08-14 07:33 UTC, sirex approved these changes

2023-08-14 07:33 UTC, merged