269 tvarkytojui priskirti duomenų rinkiniai
atviriduomenys/katalogas pull request #317
Opened 2023-05-24 07:39 UTC by Faustasm

2023-05-25 13:05 UTC, sirex requested changes

2023-05-25 13:05 UTC, sirex commented on vitrina/datasets/templates/vitrina/datasets/filters.html
> +            {% translate "Mano tvarkomi rinkiniai" %}
Turėtu rodyti, tik jei yra tvarkomų rinkinių. Dabar rodo, net jei nėra nei vieno tvarkokomo rinkinio.

2023-06-08 12:36 UTC, sirex approved these changes

2023-06-08 12:36 UTC, sirex commented on vitrina/api/migrations/0005_restore_old_icons.py
> -    ]
Turėtu būti perkeltas į kitą vietą, prie kategorijų migracijų.

2023-08-03 04:37 UTC, Faustasm commented on vitrina/api/migrations/0005_restore_old_icons.py
> -    ]
fixed

2023-08-10 05:10 UTC, closed without merging