288, 290, 293, 292, 300, 301 žodynas
atviriduomenys/katalogas pull request #318
Opened 2023-05-25 12:03 UTC by adp-atea

2023-05-29 06:32 UTC, sirex commented
![image](https://github.com/atviriduomenys/katalogas/assets/297583/e7f45937-bbde-424c-804c-a1543508dac0)

Struktūros aprašai persikelia į viršutinį meniu. „Dataset structure: [ Review ]“ reikia panaikinti ir duomenų rinkinio peržiūros metu rodyti tokį meniu:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/51c0ecbd-32e1-460b-8081-cf60a2729d29)

Nepametant „Tvarkytojai“, „Istorija“ ir „Projektai“.

2023-05-29 08:23 UTC, sirex requested changes
Matau, kad visi6kai nepadaryta CRUD dalis, nors mygtukai rodomi, tačiau juos rodo visiems įskaitant ir neprisijungusiems naudotojams.

Surašiau aptiktas klaidas prie užduočių, komentaruose.

2023-05-29 08:23 UTC, sirex commented on pyproject.toml
> +uuid = "^1.30"
Kodėl reikia `uuid` bibliotekos? Kodėl, neužtenka build-in uuid?

https://docs.python.org/3/library/uuid.html

2023-05-29 08:23 UTC, sirex commented on vitrina/structure/templates/vitrina/structure/structure_tabs.html
> +            <a href="{{ information_url }}">
Nuoroda neveikia, pasaudus ant nuorodos iš http://localhost:8000/datasets/1875/models/ gaunu:

```
Page not found (404)
No Model matches the given query.
Request Method:	GET
Request URL:	http://localhost:8000/datasets/1875/models/None/
Raised by:	vitrina.structure.views.ModelStructureView
```

2023-05-30 09:43 UTC, adp-atea commented
Dėl #300  komentarų susijusių su stiliais, turbūt nepergeneravot webpack css failų. Pergeneravus, turėtų tvarkingai rodyti.

2023-06-26 06:28 UTC, sirex approved these changes

2023-06-26 09:48 UTC, merged