144 pasikeitusių nuorodų peradresavimas 1
atviriduomenys/katalogas pull request #671
Opened 2023-10-18 10:50 UTC by Faustasm

2023-10-18 11:19 UTC, sirex requested changes

2023-10-18 11:19 UTC, sirex commented on vitrina/viisp/views.py
> +            return HttpResponse(status=500)
Gal reikėtu pridėti paaiškinimą, kas čia per klaida, vietoj to, kad grąžinti 500 klaida, be jokios žinutės? Tas, kas aiškinsis, kas čia per klaida, bus dėkingas, kad nepatingėta, paaiškinti, kas per klaida.

2023-10-18 11:19 UTC, sirex commented on vitrina/compat/migrations/0001_initial.py
> +        new_path='/requests/194/',
Jei teisingai suprantu, čia yra įhardcodintas vienas duomenų rinkinys? O kaip dėl likusių ~2000 rinkinių?

2023-10-18 11:19 UTC, sirex commented on vitrina/viisp/xml_utils.py
> +    print(soap_request)
Būtų gerai, kad kode nebūtų paliekama debug kodas.

2023-10-18 11:19 UTC, sirex commented on vitrina/viisp/xml_utils.py
> +        print(e.response.text)
Reikėtu naudoti logging, kad būtų galima valdyti tokias žinutes iš settings.py.

2023-10-20 04:03 UTC, Faustasm commented on vitrina/viisp/views.py
> +            return HttpResponse(status=500)
Pataisyta

2023-10-20 04:03 UTC, Faustasm commented on vitrina/compat/migrations/0001_initial.py
> +        new_path='/requests/194/',
Pataisyta

2023-10-20 04:03 UTC, Faustasm commented on vitrina/viisp/xml_utils.py
> +    print(soap_request)
Pataisyta

2023-10-20 04:03 UTC, Faustasm commented on vitrina/viisp/xml_utils.py
> +        print(e.response.text)
Pataisyta

2023-10-20 17:13 UTC, sirex approved these changes

2023-10-20 17:13 UTC, merged